/** Centralized backend API path constants — aligned to verified FastAPI routes. */
export const API = {
  auth: {
    login: "/auth/login",
    register: "/auth/register",
    me: "/auth/me",
    refresh: "/auth/refresh",
    logout: "/auth/logout",
    mfaSetup: "/auth/mfa/setup",
    mfaVerify: "/auth/mfa/verify",
    mfaDisable: "/auth/mfa/disable",
  },
  cases: {
    list: "/cases/",
    create: "/cases/",
    detail: (id: string) => `/cases/${id}`,
    update: (id: string) => `/cases/${id}`,
    patch: (id: string) => `/cases/${id}`,
    assign: (id: string) => `/cases/${id}/assign`,
    delete: (id: string) => `/cases/${id}`,
  },
  evidence: {
    upload: "/evidence/upload",
    list: "/evidence/",
    detail: (id: string) => `/evidence/${id}`,
    byCase: (caseId: string) => `/evidence/case/${caseId}`,
    custody: (id: string) => `/evidence/${id}/custody`,
    download: (id: string) => `/evidence/${id}/download`,
    delete: (id: string) => `/evidence/${id}`,
    reassign: (id: string) => `/evidence/${id}/reassign`,
  },
  uploads: {
    start: "/uploads/start",
    chunk: "/uploads/chunk",
    complete: "/uploads/complete",
    cancel: "/uploads/cancel",
    status: (uploadId: string) => `/uploads/status/${uploadId}`,
    resume: "/uploads/resume",
    delete: (uploadId: string) => `/uploads/${uploadId}`,
  },
  search: {
    query: "/api/v1/search",
    evidence: "/api/v1/search/evidence",
    cases: "/api/v1/search/cases",
    timeline: "/api/v1/search/timeline",
    entities: "/api/v1/search/entities",
    relationships: "/api/v1/search/relationships",
    hybrid: "/api/v1/search/hybrid",
    semantic: "/api/v1/search/semantic",
    crossCorrelate: "/api/v1/search/cross-correlation",
    reindex: "/api/v1/search/reindex",
    facets: (searchType: string) => `/api/v1/search/facets/${searchType}`,
    health: "/api/v1/search/health",
  },
  kg: {
    query: "/kg/query",
    entities: "/kg/entities",
    caseGraph: (caseId: string) => `/kg/case/${caseId}/graph`,
    entityNeighbors: (entityType: string, entityName: string) =>
      `/kg/entity/${entityType}/${encodeURIComponent(entityName)}/neighbors`,
    caseSync: (caseId: string) => `/kg/case/${caseId}/sync`,
    ingestEvidence: (evidenceId: string) =>
      `/kg/ingest/evidence/${evidenceId}`,
  },
  ai: {
    query: "/ai/agent/query",
    ingest: "/ai/ingest",
    document: (docId: string) => `/ai/documents/${docId}`,
  },
  workspace: {
    detail: (caseId: string) => `/workspace/cases/${caseId}`,
    evidence: (caseId: string) => `/workspace/cases/${caseId}/evidence`,
    custody: (caseId: string) => `/workspace/cases/${caseId}/custody`,
    timeline: (caseId: string) => `/workspace/cases/${caseId}/timeline`,
    progress: (caseId: string) => `/workspace/cases/${caseId}/progress`,
    risks: (caseId: string) => `/workspace/cases/${caseId}/risks`,
    kgSummary: (caseId: string) => `/workspace/cases/${caseId}/kg-summary`,
    aiFindings: (caseId: string) => `/workspace/cases/${caseId}/ai-findings`,
    courtReport: (caseId: string) => `/workspace/cases/${caseId}/court-report`,
  },
  timeline: {
    list: "/timeline",
  },
  processing: {
    enqueue: (evidenceId: string) =>
      `/processing/evidence/${evidenceId}/enqueue`,
    job: (jobId: string) => `/processing/jobs/${jobId}`,
    cancelJob: (jobId: string) => `/processing/jobs/${jobId}/cancel`,
    jobProgress: (jobId: string) => `/processing/jobs/${jobId}/progress`,
    queueStats: "/processing/queue/stats",
    forensic: (evidenceId: string) => `/processing/forensic/${evidenceId}`,
    processors: "/processing/forensic/processors",
  },
  distributed: {
    enqueueTask: "/api/v1/distributed/tasks",
    enqueueBatch: "/api/v1/distributed/tasks/batch",
    taskProgress: (taskId: string) => `/api/v1/distributed/tasks/${taskId}/progress`,
    cancelTask: (taskId: string) => `/api/v1/distributed/tasks/${taskId}/cancel`,
    retryTask: (taskId: string) => `/api/v1/distributed/tasks/${taskId}/retry`,
    job: (jobId: string) => `/api/v1/distributed/jobs/${jobId}`,
    cancelJob: (jobId: string) => `/api/v1/distributed/jobs/${jobId}/cancel`,
    resumeJob: (jobId: string) => `/api/v1/distributed/jobs/${jobId}/resume`,
    queueDepth: "/api/v1/distributed/queue/depth",
    workers: "/api/v1/distributed/workers",
    worker: (workerId: string) => `/api/v1/distributed/workers/${workerId}`,
    metrics: "/api/v1/distributed/metrics",
    dlq: "/api/v1/distributed/dlq",
    dlqReplay: (taskId: string) => `/api/v1/distributed/dlq/${taskId}/replay`,
    dlqPurge: "/api/v1/distributed/dlq",
  },
  reports: {
    create: "/reports",
    byCase: (caseId: string) => `/reports/${caseId}`,
    detail: (reportId: string) => `/reports/detail/${reportId}`,
    delete: (reportId: string) => `/reports/${reportId}`,
    exportPdf: (reportId: string) => `/reports/${reportId}/export/pdf`,
    exportDocx: (reportId: string) => `/reports/${reportId}/export/docx`,
    exportJson: (reportId: string) => `/reports/${reportId}/export/json`,
    exportZip: (reportId: string) => `/reports/${reportId}/export/zip`,
  },
  compliance: {
    gdprDelete: "/api/v1/compliance/gdpr/delete",
    gdprStatus: (userId: string) => `/api/v1/compliance/gdpr/status/${userId}`,
    retentionPolicies: "/api/v1/compliance/retention/policies",
    retentionPolicy: (policyId: string) =>
      `/api/v1/compliance/retention/policies/${policyId}`,
    retentionExecute: "/api/v1/compliance/retention/execute",
    legalHold: "/api/v1/compliance/legal-hold",
    legalHoldItem: (holdId: string) => `/api/v1/compliance/legal-hold/${holdId}`,
    legalHoldCheck: (entityType: string, entityId: string) =>
      `/api/v1/compliance/legal-hold/check/${entityType}/${entityId}`,
    reportsGenerate: "/api/v1/compliance/reports/generate",
    reports: "/api/v1/compliance/reports",
    classification: "/api/v1/compliance/classification",
    classificationGet: (entityType: string, entityId: string) =>
      `/api/v1/compliance/classification/${entityType}/${entityId}`,
    verifyChain: "/api/v1/compliance/audit/verify-chain",
    exportEvidence: (evidenceId: string) =>
      `/api/v1/compliance/export/evidence/${evidenceId}`,
    exportCase: (caseId: string) => `/api/v1/compliance/export/case/${caseId}`,
  },
  roles: {
    assign: "/roles/assign",
    revoke: "/roles/revoke",
    users: "/roles/users",
    bootstrapAdmin: "/roles/bootstrap-admin",
  },
  apiKeys: {
    list: "/api-keys",
    create: "/api-keys",
    revoke: (keyId: string) => `/api-keys/${keyId}`,
    rotate: (keyId: string) => `/api-keys/${keyId}/rotate`,
  },
  tenants: {
    organizations: "/api/v1/tenants/organizations",
    organization: (orgId: string) => `/api/v1/tenants/organizations/${orgId}`,
    projects: (orgId: string) => `/api/v1/tenants/organizations/${orgId}/projects`,
    project: (orgId: string, projectId: string) =>
      `/api/v1/tenants/organizations/${orgId}/projects/${projectId}`,
    members: (orgId: string) => `/api/v1/tenants/organizations/${orgId}/members`,
    member: (orgId: string, userId: string) =>
      `/api/v1/tenants/organizations/${orgId}/members/${userId}`,
    usage: (orgId: string) => `/api/v1/tenants/organizations/${orgId}/usage`,
  },
  tsk: {
    capabilities: "/tsk/capabilities",
    process: "/tsk/process",
    enqueue: "/tsk/enqueue",
    status: (jobId: string) => `/tsk/status/${jobId}`,
  },
  health: {
    root: "/health",
    ready: "/health/ready",
    live: "/health/live",
    detailed: "/health/detailed",
  },
  observability: {
    metrics: "/metrics",
    metricsJson: "/metrics/json",
  },
} as const;
